# Generated by Django 3.1.7 on 2021-03-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='slug',
            field=models.SlugField(default=None, max_length=128, null=True, unique=True),
        ),
    ]
