# Generated by Django 3.1.7 on 2021-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0002_auto_20210312_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupe',
            options={'ordering': ['category']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_add']},
        ),
        migrations.AddField(
            model_name='messages',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
