# Generated by Django 3.1.7 on 2021-03-17 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal_app', '0004_groupe_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='to_join',
            field=models.ManyToManyField(related_name='groups_to_join', to=settings.AUTH_USER_MODEL),
        ),
    ]
