# Generated by Django 3.1.7 on 2021-04-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0006_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='groupe',
        ),
    ]
