# Generated by Django 3.1.7 on 2021-03-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0006_auto_20210312_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='upper_class_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_app.category'),
        ),
    ]
