# Generated by Django 3.1.7 on 2021-03-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_app', '0007_auto_20210312_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=None, max_length=128, null=True),
        ),
    ]
